name: Terraform Destroy

on:
  workflow_dispatch:   # ✅ Trigger manually from GitHub Actions tab
  # You can also schedule if you want automatic cleanup
  # schedule:
  #   - cron: "0 2 * * *"   # runs daily at 2AM UTC

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform -chdir=infrastructure init

      # ⚠️ Destroy everything
      - name: Terraform Destroy
        run: terraform -chdir=infrastructure destroy -auto-approve
